EXAM_TYPE = {'PURE_TONE': 'PURE_TONE', 'DICHOTIC_DIGIT': 'DICHOTIC_DIGIT', 'SPEECH_IN_NOISE': 'SPEECH_IN_NOISE'}
ROLES = {'ADMIN': 'ADMIN', 'USER': 'USER'}

EXAM_STATUS = {'DONE': 'DONE', 'PENDING': 'PENDING'}
